(function () {
  var languageKeys = { English: "en", German: "de", Slovak: "sk", Spanish: "es", Czech: "cs", Polish: "pl", Portuguese: "pt", Italian: "it" };
  var messageTranslations = {
    "Please select a country.": { de: "Bitte wähle ein Land aus.", sk: "Vyberte krajinu.", es: "Selecciona un país.", cs: "Vyberte zemi.", pl: "Wybierz kraj.", pt: "Selecione um país.", it: "Seleziona un paese." },
    "Please select at least one subject.": { de: "Bitte wähle mindestens ein Fach aus.", sk: "Vyberte aspoň jeden predmet.", es: "Selecciona al menos una asignatura.", cs: "Vyberte alespoň jeden předmět.", pl: "Wybierz co najmniej jeden przedmiot.", pt: "Selecione pelo menos uma disciplina.", it: "Seleziona almeno una materia." },
    "Please upload your lesson plan.": { de: "Bitte lade deinen Lesson Plan hoch.", sk: "Nahrajte svoj plán vyučovania.", es: "Sube tu plan de clase.", cs: "Nahrajte svůj plán lekce.", pl: "Prześlij swój plan lekcji.", pt: "Carregue o seu plano de aula.", it: "Carica il tuo piano di lezione." },
    "Please enter at least one grade.": { de: "Bitte gib mindestens eine Schulstufe ein.", sk: "Zadajte aspoň jeden ročník.", es: "Introduce al menos un curso.", cs: "Zadejte alespoň jeden ročník.", pl: "Podaj co najmniej jedną klasę.", pt: "Introduza pelo menos um ano escolar.", it: "Inserisci almeno una classe." },
    "Please enter a valid grade value.": { de: "Bitte gib eine gültige Schulstufe ein.", sk: "Zadajte platný ročník.", es: "Introduce un curso válido.", cs: "Zadejte platný ročník.", pl: "Podaj prawidłową klasę.", pt: "Introduza um ano válido.", it: "Inserisci una classe valida." },
    "Please enter a valid age value.": { de: "Bitte gib ein gültiges Alter ein.", sk: "Zadajte platný vek.", es: "Introduce una edad válida.", cs: "Zadejte platný věk.", pl: "Podaj prawidłowy wiek.", pt: "Introduza uma idade válida.", it: "Inserisci un'età valida." },
    "Please make sure the grade range is valid.": { de: "Bitte stelle sicher, dass der Schulstufenbereich gültig ist.", sk: "Skontrolujte, či je rozsah ročníkov platný.", es: "Asegúrate de que el intervalo de cursos sea válido.", cs: "Ověřte, že je rozsah ročníků platný.", pl: "Upewnij się, że zakres klas jest prawidłowy.", pt: "Verifique se o intervalo de anos é válido.", it: "Assicurati che l'intervallo delle classi sia valido." },
    "Mistral API key configured": { de: "Mistral-API-Key ist eingerichtet", sk: "Kľúč Mistral API je nastavený", es: "Clave API de Mistral configurada", cs: "Klíč Mistral API je nastaven", pl: "Klucz API Mistral jest skonfigurowany", pt: "Chave API Mistral configurada", it: "Chiave API Mistral configurata" },
    "Mistral API key missing": { de: "Mistral-API-Key fehlt", sk: "Chýba kľúč Mistral API", es: "Falta la clave API de Mistral", cs: "Chybí klíč Mistral API", pl: "Brak klucza API Mistral", pt: "Falta a chave API Mistral", it: "Chiave API Mistral mancante" },
    "DOCX/PDF export packages available": { de: "DOCX-/PDF-Exportpakete verfügbar", sk: "Balíky na export DOCX/PDF sú dostupné", es: "Paquetes de exportación DOCX/PDF disponibles", cs: "Balíčky pro export DOCX/PDF jsou dostupné", pl: "Pakiety eksportu DOCX/PDF są dostępne", pt: "Pacotes de exportação DOCX/PDF disponíveis", it: "Pacchetti di esportazione DOCX/PDF disponibili" },
    "Local tutor folders ready": { de: "Lokale Tutor-Ordner bereit", sk: "Miestne priečinky tutora sú pripravené", es: "Carpetas locales del tutor listas", cs: "Místní složky tutora jsou připravené", pl: "Lokalne foldery tutora są gotowe", pt: "Pastas locais do tutor prontas", it: "Cartelle locali del tutor pronte" },
    "Python runtime unavailable": { de: "Python-Laufzeit nicht verfügbar", sk: "Python runtime nie je dostupný", es: "Entorno de Python no disponible", cs: "Python runtime není k dispozici", pl: "Środowisko Python niedostępne", pt: "Runtime Python indisponível", it: "Runtime Python non disponibile" },
    "Ready": { de: "Bereit", sk: "Pripravené", es: "Listo", cs: "Připraveno", pl: "Gotowe", pt: "Pronto", it: "Pronto" },
    "Action required": { de: "Aktion erforderlich", sk: "Vyžaduje sa akcia", es: "Se requiere una acción", cs: "Je vyžadována akce", pl: "Wymagane działanie", pt: "É necessária uma ação", it: "Azione richiesta" }
    ,"Select country": { de: "Land auswählen", sk: "Vyberte krajinu", es: "Selecciona un país", cs: "Vyberte zemi", pl: "Wybierz kraj", pt: "Selecione o país", it: "Seleziona il paese" }
    ,"From": { de: "Von", sk: "Od", es: "Desde", cs: "Od", pl: "Od", pt: "De", it: "Da" }
    ,"To": { de: "Bis", sk: "Do", es: "Hasta", cs: "Do", pl: "Do", pt: "Até", it: "A" }
    ,"To (optional)": { de: "Bis (optional)", sk: "Do (voliteľné)", es: "Hasta (opcional)", cs: "Do (volitelné)", pl: "Do (opcjonalnie)", pt: "Até (opcional)", it: "A (opzionale)" }
    ,"Any specific information we should know?": { de: "Gibt es besondere Informationen?", sk: "Sú nejaké špecifické informácie?", es: "¿Hay alguna información específica que debamos conocer?", cs: "Je něco konkrétního, co bychom měli vědět?", pl: "Czy są jakieś szczególne informacje?", pt: "Há alguma informação específica que devamos saber?", it: "Ci sono informazioni specifiche che dovremmo sapere?" }
    ,"No prompt files found.": { de: "Keine Prompt-Dateien gefunden.", sk: "Nenašli sa žiadne súbory promptov.", es: "No se encontraron archivos de prompts.", cs: "Nebyly nalezeny žádné soubory promptů.", pl: "Nie znaleziono plików promptów.", pt: "Não foram encontrados ficheiros de prompts.", it: "Nessun file di prompt trovato." }
    ,"Other": { de: "Andere", sk: "Iné", es: "Otro", cs: "Jiné", pl: "Inne", pt: "Outro", it: "Altro" }
    ,"Spain": { de: "Spanien", sk: "Španielsko", es: "España", cs: "Španělsko", pl: "Hiszpania", pt: "Espanha", it: "Spagna" }
    ,"Germany": { de: "Deutschland", sk: "Nemecko", es: "Alemania", cs: "Německo", pl: "Niemcy", pt: "Alemanha", it: "Germania" }
    ,"Austria": { de: "Österreich", sk: "Rakúsko", es: "Austria", cs: "Rakousko", pl: "Austria", pt: "Áustria", it: "Austria" }
    ,"Slovakia": { de: "Slowakei", sk: "Slovensko", es: "Eslovaquia", cs: "Slovensko", pl: "Słowacja", pt: "Eslováquia", it: "Slovacchia" }
    ,"Mathematics": { de: "Mathematik", sk: "Matematika", es: "Matemáticas", cs: "Matematika", pl: "Matematyka", pt: "Matemática", it: "Matematica" }
    ,"Informatics / CS": { de: "Informatik / CS", sk: "Informatika / informatika", es: "Informática / CS", cs: "Informatika / informatika", pl: "Informatyka / CS", pt: "Informática / CS", it: "Informatica / CS" }
    ,"Biology": { de: "Biologie", sk: "Biológia", es: "Biología", cs: "Biologie", pl: "Biologia", pt: "Biologia", it: "Biologia" }
    ,"Physics": { de: "Physik", sk: "Fyzika", es: "Física", cs: "Fyzika", pl: "Fizyka", pt: "Física", it: "Fisica" }
    ,"Chemistry": { de: "Chemie", sk: "Chémia", es: "Química", cs: "Chemie", pl: "Chemia", pt: "Química", it: "Chimica" }
    ,"Review the points below. Select what you would like us to focus on in the next step. You can also add more details or clarify if needed.": { de: "Prüfe die folgenden Punkte. Wähle aus, worauf wir uns im nächsten Schritt konzentrieren sollen. Du kannst außerdem Details ergänzen oder etwas klarstellen.", sk: "Prezrite si body nižšie. Vyberte, na čo sa máme zamerať v ďalšom kroku. V prípade potreby môžete doplniť podrobnosti alebo niečo objasniť.", es: "Revisa los puntos siguientes. Selecciona en qué quieres que nos centremos después. También puedes añadir detalles o aclaraciones.", cs: "Prohlédněte si níže uvedené body. Vyberte, na co se máme zaměřit v dalším kroku. V případě potřeby můžete doplnit podrobnosti nebo něco upřesnit.", pl: "Przejrzyj poniższe punkty. Wybierz, na czym mamy skupić się w następnym kroku. Możesz też dodać szczegóły lub wyjaśnienia.", pt: "Reveja os pontos abaixo. Selecione aquilo em que devemos focar no próximo passo. Também pode adicionar detalhes ou esclarecimentos.", it: "Esamina i punti seguenti. Seleziona su cosa concentrarci nel prossimo passaggio. Puoi anche aggiungere dettagli o chiarimenti." }
    ,"We analyzed your uploaded lesson plan and identified the points below.": { de: "Wir haben deinen hochgeladenen Lesson Plan analysiert und die folgenden Punkte identifiziert.", sk: "Analyzovali sme váš nahraný plán vyučovania a identifikovali sme nasledujúce body.", es: "Hemos analizado tu plan de clase y hemos identificado los puntos siguientes.", cs: "Analyzovali jsme váš nahraný plán lekce a identifikovali následující body.", pl: "Przeanalizowaliśmy przesłany plan lekcji i zidentyfikowaliśmy poniższe punkty.", pt: "Analisámos o seu plano de aula e identificámos os pontos abaixo.", it: "Abbiamo analizzato il piano di lezione caricato e identificato i punti seguenti." }
    ,"Uploaded file": { de: "Hochgeladene Datei", sk: "Nahraný súbor", es: "Archivo cargado", cs: "Nahraný soubor", pl: "Przesłany plik", pt: "Ficheiro carregado", it: "File caricato" }
    ,"Detected subjects": { de: "Erkannte Fächer", sk: "Identifikované predmety", es: "Asignaturas detectadas", cs: "Zjištěné předměty", pl: "Wykryte przedmioty", pt: "Disciplinas detetadas", it: "Materie rilevate" }
    ,"Detected grade range": { de: "Erkannter Schulstufenbereich", sk: "Identifikovaný rozsah ročníkov", es: "Intervalo de cursos detectado", cs: "Zjištěný rozsah ročníků", pl: "Wykryty zakres klas", pt: "Intervalo de anos detetado", it: "Intervallo di classi rilevato" }
    ,"Detected age range": { de: "Erkannter Altersbereich", sk: "Identifikovaný vekový rozsah", es: "Intervalo de edad detectado", cs: "Zjištěný věkový rozsah", pl: "Wykryty zakres wieku", pt: "Intervalo de idades detetado", it: "Intervallo di età rilevato" }
    ,"CT practice": { de: "CT-Praxis", sk: "CT postup", es: "Práctica de PC", cs: "Praxe CT", pl: "Praktyka CT", pt: "Prática de CT", it: "Pratica CT" }
    ,"Status": { de: "Status", sk: "Stav", es: "Estado", cs: "Stav", pl: "Status", pt: "Estado", it: "Stato" }
    ,"Associated activity": { de: "Zugehörige Aktivität", sk: "Súvisiaca aktivita", es: "Actividad asociada", cs: "Související aktivita", pl: "Powiązana aktywność", pt: "Atividade associada", it: "Attività associata" }
    ,"Discussion / clarification": { de: "Diskussion / Klarstellung", sk: "Diskusia / objasnenie", es: "Debate / aclaración", cs: "Diskuse / upřesnění", pl: "Dyskusja / wyjaśnienie", pt: "Discussão / esclarecimento", it: "Discussione / chiarimento" }
    ,"Focus on this?": { de: "Darauf fokussieren?", sk: "Zamerať sa na toto?", es: "¿Centrarse en esto?", cs: "Zaměřit se na toto?", pl: "Skupić się na tym?", pt: "Focar nisto?", it: "Concentrarsi su questo?" }
    ,"Identified point": { de: "Identifizierter Punkt", sk: "Identifikovaný bod", es: "Punto identificado", cs: "Identifikovaný bod", pl: "Zidentyfikowany punkt", pt: "Ponto identificado", it: "Punto identificato" }
    ,"Why we mentioned this": { de: "Warum wir das erwähnen", sk: "Prečo to spomíname", es: "Por qué lo mencionamos", cs: "Proč to zmiňujeme", pl: "Dlaczego o tym wspominamy", pt: "Porque mencionámos isto", it: "Perché lo menzioniamo" }
    ,"Citation from your text": { de: "Zitat aus deinem Text", sk: "Citácia z vášho textu", es: "Cita de tu texto", cs: "Citace z vašeho textu", pl: "Cytat z Twojego tekstu", pt: "Citação do seu texto", it: "Citazione dal tuo testo" }
    ,"Confidence": { de: "Sicherheit", sk: "Miera istoty", es: "Confianza", cs: "Jistota", pl: "Pewność", pt: "Confiança", it: "Affidabilità" }
    ,"Discussion": { de: "Diskussion", sk: "Diskusia", es: "Debate", cs: "Diskuse", pl: "Dyskusja", pt: "Discussão", it: "Discussione" }
    ,"Add clarification...": { de: "Klarstellung hinzufügen ...", sk: "Pridajte objasnenie ...", es: "Añadir aclaración...", cs: "Přidat upřesnění...", pl: "Dodaj wyjaśnienie...", pt: "Adicionar esclarecimento...", it: "Aggiungi chiarimento..." }
    ,"You: ": { de: "Du: ", sk: "Vy: ", es: "Tú: ", cs: "Vy: ", pl: "Ty: ", pt: "Você: ", it: "Tu: " }
    ,"Tutor: ": { de: "Tutor: ", sk: "Tutor: ", es: "Tutor: ", cs: "Tutor: ", pl: "Tutor: ", pt: "Tutor: ", it: "Tutor: " }
    ,"Send": { de: "Senden", sk: "Odoslať", es: "Enviar", cs: "Odeslat", pl: "Wyślij", pt: "Enviar", it: "Invia" }
    ,"Decision:": { de: "Entscheidung:", sk: "Rozhodnutie:", es: "Decisión:", cs: "Rozhodnutí:", pl: "Decyzja:", pt: "Decisão:", it: "Decisione:" }
    ,"Include in download": { de: "In Download aufnehmen", sk: "Zahrnúť do stiahnutia", es: "Incluir en la descarga", cs: "Zahrnout do stažení", pl: "Uwzględnij w pobraniu", pt: "Incluir no download", it: "Includi nel download" }
    ,"Open": { de: "Offen", sk: "Otvorené", es: "Abierta", cs: "Otevřené", pl: "Otwarte", pt: "Aberto", it: "Aperta" }
    ,"No citation": { de: "Kein Zitat", sk: "Žiadna citácia", es: "Sin cita", cs: "Bez citace", pl: "Brak cytatu", pt: "Sem citação", it: "Nessuna citazione" }
    ,"Raw response:": { de: "Rohantwort:", sk: "Surová odpoveď:", es: "Respuesta sin procesar:", cs: "Surová odpověď:", pl: "Surowa odpowiedź:", pt: "Resposta bruta:", it: "Risposta grezza:" }
    ,"to": { de: "bis", sk: "do", es: "a", cs: "do", pl: "do", pt: "a", it: "a" }
    ,"Confidence:": { de: "Sicherheit:", sk: "Miera istoty:", es: "Confianza:", cs: "Jistota:", pl: "Pewność:", pt: "Confiança:", it: "Affidabilità:" }
    ,"Match:": { de: "Übereinstimmung:", sk: "Zhoda:", es: "Coincidencia:", cs: "Shoda:", pl: "Dopasowanie:", pt: "Correspondência:", it: "Corrispondenza:" }
    ,"unclear": { de: "unklar", sk: "nejasné", es: "no claro", cs: "nejasné", pl: "niejasne", pt: "incerto", it: "non chiaro" }
    ,"Not detected": { de: "Nicht erkannt", sk: "Neidentifikované", es: "No detectado", cs: "Nezjištěno", pl: "Nie wykryto", pt: "Não detetado", it: "Non rilevato" }
    ,"No metadata available.": { de: "Keine Metadaten verfügbar.", sk: "Metadáta nie sú k dispozícii.", es: "No hay metadatos disponibles.", cs: "Metadata nejsou k dispozici.", pl: "Brak dostępnych metadanych.", pt: "Não há metadados disponíveis.", it: "Nessun metadato disponibile." }
    ,"Time scope": { de: "Zeitumfang", sk: "Časový rozsah", es: "Duración", cs: "Časový rozsah", pl: "Zakres czasowy", pt: "Duração", it: "Durata" }
    ,"Goals / competencies": { de: "Ziele / Kompetenzen", sk: "Ciele / kompetencie", es: "Objetivos / competencias", cs: "Cíle / kompetence", pl: "Cele / kompetencje", pt: "Objetivos / competências", it: "Obiettivi / competenze" }
    ,"Adaptability": { de: "Anpassungsfähigkeit", sk: "Prispôsobiteľnosť", es: "Adaptabilidad", cs: "Přizpůsobivost", pl: "Możliwość dostosowania", pt: "Adaptabilidade", it: "Adattabilità" }
    ,"Detail level": { de: "Detailgrad", sk: "Úroveň podrobnosti", es: "Nivel de detalle", cs: "Úroveň podrobnosti", pl: "Poziom szczegółowości", pt: "Nível de detalhe", it: "Livello di dettaglio" }
    ,"Target group": { de: "Zielgruppe", sk: "Cieľová skupina", es: "Grupo destinatario", cs: "Cílová skupina", pl: "Grupa docelowa", pt: "Grupo-alvo", it: "Gruppo target" }
    ,"Curriculum alignment": { de: "Lehrplanbezug", sk: "Súlad s učebnými osnovami", es: "Alineación curricular", cs: "Soulad s učebními plány", pl: "Zgodność z programem", pt: "Alinhamento curricular", it: "Allineamento curricolare" }
    ,"high": { de: "hoch", sk: "vysoká", es: "alta", cs: "vysoká", pl: "wysoka", pt: "alta", it: "alta" }
    ,"medium": { de: "mittel", sk: "stredná", es: "media", cs: "střední", pl: "średnia", pt: "média", it: "media" }
    ,"low": { de: "niedrig", sk: "nízka", es: "baja", cs: "nízká", pl: "niska", pt: "baixa", it: "bassa" }
    ,"File:": { de: "Datei:", sk: "Súbor:", es: "Archivo:", cs: "Soubor:", pl: "Plik:", pt: "Ficheiro:", it: "File:" }
    ,"Country:": { de: "Land:", sk: "Krajina:", es: "País:", cs: "Země:", pl: "Kraj:", pt: "País:", it: "Paese:" }
    ,"Subjects:": { de: "Fächer:", sk: "Predmety:", es: "Asignaturas:", cs: "Předměty:", pl: "Przedmioty:", pt: "Disciplinas:", it: "Materie:" }
    ,"Grades:": { de: "Schulstufen:", sk: "Ročníky:", es: "Cursos:", cs: "Ročníky:", pl: "Klasy:", pt: "Anos:", it: "Classi:" }
    ,"Age:": { de: "Alter:", sk: "Vek:", es: "Edad:", cs: "Věk:", pl: "Wiek:", pt: "Idade:", it: "Età:" }
    ,"Specifics:": { de: "Zusätzliche Angaben:", sk: "Špecifiká:", es: "Detalles:", cs: "Upřesnění:", pl: "Szczegóły:", pt: "Especificidades:", it: "Dettagli:" }
  };
  var translations = [
    [".header-subtitle", "AI Tutor for Lesson Plans", { de: "KI-Tutor für Unterrichtspläne", sk: "AI tutor pre prípravy na vyučovanie", es: "Tutor de IA para planes de clase", cs: "AI tutor pro přípravy na vyučování", pl: "Tutor AI do planów lekcji", pt: "Tutor de IA para planos de aula", it: "Tutor IA per piani di lezione" }],
    [".header-note", "Prototype 1.0", { de: "Prototyp 1.0", sk: "Prototyp 1.0", es: "Prototipo 1.0", cs: "Prototyp 1.0", pl: "Prototyp 1.0", pt: "Protótipo 1.0", it: "Prototipo 1.0" }],
    ["#moreInfoButton", "Need more information?", { de: "Mehr Informationen?", sk: "Potrebujete viac informácií?", es: "¿Necesitas más información?", cs: "Potřebujete více informací?", pl: "Potrzebujesz więcej informacji?", pt: "Precisa de mais informações?", it: "Servono più informazioni?" }],
    [".progress-step:nth-of-type(1) .step-label", "Tell us about your lesson idea", { de: "Erzähle uns von deiner Unterrichtsidee", sk: "Povedzte nám o svojej vyučovacej myšlienke", es: "Cuéntanos tu idea de clase", cs: "Řekněte nám svůj nápad na lekci", pl: "Opowiedz nam o swoim pomyśle na lekcję", pt: "Conte-nos a sua ideia de aula", it: "Raccontaci la tua idea di lezione" }],
    [".progress-step:nth-of-type(2) .step-label", "First analysis and suggestions", { de: "Erste Analyse und Vorschläge", sk: "Prvá analýza a návrhy", es: "Primer análisis y sugerencias", cs: "První analýza a návrhy", pl: "Pierwsza analiza i sugestie", pt: "Primeira análise e sugestões", it: "Prima analisi e suggerimenti" }],
    [".progress-step:nth-of-type(3) .step-label", "Refining and improving", { de: "Überarbeiten und verbessern", sk: "Úprava a zlepšovanie", es: "Perfeccionar y mejorar", cs: "Úprava a zlepšování", pl: "Udoskonalanie i poprawa", pt: "Aperfeiçoar e melhorar", it: "Raffinare e migliorare" }],
    [".progress-step:nth-of-type(4) .step-label", "Download result", { de: "Ergebnis herunterladen", sk: "Stiahnuť výsledok", es: "Descargar resultado", cs: "Stáhnout výsledek", pl: "Pobierz wynik", pt: "Descarregar resultado", it: "Scarica risultato" }],
    ["#startButton .button-text", "I understand and want to proceed", { de: "Ich verstehe und möchte fortfahren", sk: "Rozumiem a chcem pokračovať", es: "Lo entiendo y quiero continuar", cs: "Rozumím a chci pokračovat", pl: "Rozumiem i chcę kontynuować", pt: "Compreendo e quero continuar", it: "Ho capito e voglio continuare" }],
    ["#infoButton .button-text", "I need more information", { de: "Ich brauche mehr Informationen", sk: "Potrebujem viac informácií", es: "Necesito más información", cs: "Potřebuji více informací", pl: "Potrzebuję więcej informacji", pt: "Preciso de mais informações", it: "Ho bisogno di maggiori informazioni" }],
    ["#projectButton .button-text", "Information about the project", { de: "Informationen über das Projekt", sk: "Informácie o projekte", es: "Información sobre el proyecto", cs: "Informace o projektu", pl: "Informacje o projekcie", pt: "Informações sobre o projeto", it: "Informazioni sul progetto" }],
    ["#settingsButton .button-text", "Admin settings", { de: "Admin-Einstellungen", sk: "Nastavenia správcu", es: "Configuración de administración", cs: "Nastavení správce", pl: "Ustawienia administratora", pt: "Definições de administração", it: "Impostazioni amministratore" }],
    ["#configureApiKeyButton .button-text", "Open Admin settings", { de: "Admin-Einstellungen öffnen", sk: "Otvoriť nastavenia správcu", es: "Abrir configuración de administración", cs: "Otevřít nastavení správce", pl: "Otwórz ustawienia administratora", pt: "Abrir definições de administração", it: "Apri impostazioni amministratore" }],
    [".start-card h1", "Welcome!", { de: "Willkommen!", sk: "Vitajte!", es: "¡Bienvenido!", cs: "Vítejte!", pl: "Witamy!", pt: "Bem-vindo!", it: "Benvenuto!" }],
    [".start-card p.description:nth-of-type(1)", "Prototype 1.0 of an AI tutor that provides feedback on lesson plans.", { de: "Prototyp 1.0 eines KI-Tutors, der Feedback zu Lesson Plans gibt.", sk: "Prototyp 1.0 AI tutora, ktorý poskytuje spätnú väzbu k plánom vyučovania.", es: "Prototipo 1.0 de un tutor de IA que ofrece comentarios sobre planes de clase.", cs: "Prototyp 1.0 AI tutora poskytujícího zpětnou vazbu k plánům lekcí.", pl: "Prototyp 1.0 tutora AI udzielającego informacji zwrotnych o planach lekcji.", pt: "Protótipo 1.0 de um tutor de IA que fornece feedback sobre planos de aula.", it: "Prototipo 1.0 di un tutor IA che fornisce feedback sui piani di lezione." }],
    [".start-card p.description:nth-of-type(2)", "Tell us the country of the lesson plan, the children's grade level, and the subject, then upload your lesson plan. Important: remove all personal information first. No names and no clues about who the children are; upload only your own work. The children's rights and copyright must be respected.", { de: "Gib das Land des Lehrplans, die Schulstufe der Kinder sowie das Fach an und lade deine Unterrichtsvorbereitung hoch. Wichtig! Entferne davor alle persönlichen Daten. Keine Namen, keine Hinweise darauf, wer die Kinder sind, nur deine eigenen Arbeiten. Die Rechte der Kinder und das Urheberrecht müssen gewahrt bleiben.", sk: "Uveďte krajinu, ročník detí a predmet a potom nahrajte plán vyučovania. Dôležité! Najprv odstráňte všetky osobné údaje. Žiadne mená ani náznaky, o ktoré deti ide; nahrajte iba vlastnú prácu. Musia byť rešpektované práva detí a autorské práva.", es: "Indica el país del plan, el curso de los niños y la asignatura, y después sube tu plan. Importante: elimina antes todos los datos personales. No incluyas nombres ni pistas sobre quiénes son los niños; sube únicamente tu propio trabajo. Deben respetarse los derechos de los niños y los derechos de autor.", cs: "Uveďte zemi plánu, ročník dětí a předmět a poté nahrajte svůj plán. Důležité: nejprve odstraňte všechny osobní údaje. Neuvádějte jména ani náznaky, o které děti jde; nahrajte pouze vlastní práci. Je nutné respektovat práva dětí a autorská práva.", pl: "Podaj kraj, klasę dzieci i przedmiot, a następnie prześlij plan lekcji. Ważne: najpierw usuń wszystkie dane osobowe. Bez nazwisk i wskazówek, kim są dzieci; prześlij wyłącznie własną pracę. Należy respektować prawa dzieci i prawa autorskie.", pt: "Indique o país do plano, o ano escolar das crianças e a disciplina e, em seguida, carregue o seu plano. Importante: remova primeiro todos os dados pessoais. Não inclua nomes nem pistas sobre quem são as crianças; carregue apenas o seu próprio trabalho. Os direitos das crianças e os direitos de autor devem ser respeitados.", it: "Indica il paese del piano, la classe dei bambini e la materia, poi carica il tuo piano. Importante: prima rimuovi tutti i dati personali. Niente nomi né indizi sull'identità dei bambini; carica solo il tuo lavoro. Devono essere rispettati i diritti dei bambini e il diritto d'autore." }],
    [".start-card p.description:nth-of-type(3)", "You are welcome to use your native language of course ;)", { de: "Du kannst natürlich deine Muttersprache verwenden ;)", sk: "Samozrejme môžete používať svoj materinský jazyk ;)", es: "Por supuesto, puedes usar tu lengua materna ;)", cs: "Samozřejmě můžete používat svůj mateřský jazyk ;)", pl: "Oczywiście możesz używać swojego języka ojczystego ;)", pt: "Pode naturalmente usar a sua língua materna ;)", it: "Puoi naturalmente usare la tua lingua madre ;)" }],
    [".lesson-card .section-heading h1", "Please answer these questions", { de: "Bitte beantworte diese Fragen", sk: "Odpovedzte na tieto otázky", es: "Responde a estas preguntas", cs: "Odpovězte na tyto otázky", pl: "Odpowiedz na te pytania", pt: "Responda a estas perguntas", it: "Rispondi a queste domande" }],
    [".lesson-card .section-text", "The more information you provide, the better the feedback will be. Fields marked with * are mandatory.", { de: "Je mehr Informationen du angibst, desto besser wird das Feedback. Mit * markierte Felder sind Pflichtfelder.", sk: "Čím viac informácií uvediete, tým lepšia bude spätná väzba. Polia označené * sú povinné.", es: "Cuanta más información proporciones, mejores serán los comentarios. Los campos marcados con * son obligatorios.", cs: "Čím více informací uvedete, tím lepší bude zpětná vazba. Pole označená * jsou povinná.", pl: "Im więcej informacji podasz, tym lepsza będzie informacja zwrotna. Pola oznaczone * są obowiązkowe.", pt: "Quanto mais informações fornecer, melhor será o feedback. Os campos marcados com * são obrigatórios.", it: "Più informazioni fornisci, più preciso sarà il feedback. I campi contrassegnati con * sono obbligatori." }],
    [".country-inline-row label", "* Country", { de: "* Land", sk: "* Krajina", es: "* País", cs: "* Země", pl: "* Kraj", pt: "* País", it: "* Paese" }],
    [".subject-field .field-label-row label", "* Subject(s)", { de: "* Fach/Fächer", sk: "* Predmet(y)", es: "* Asignatura(s)", cs: "* Předmět(y)", pl: "* Przedmiot(y)", pt: "* Disciplina(s)", it: "* Materia/e" }],
    [".subject-field .field-helper", "You can select more than one.", { de: "Du kannst mehrere auswählen.", sk: "Môžete vybrať viac položiek.", es: "Puedes seleccionar más de una.", cs: "Můžete vybrat více možností.", pl: "Możesz wybrać więcej niż jeden.", pt: "Pode selecionar mais do que uma.", it: "Puoi selezionarne più di una." }],
    [".context-fields .half:first-child label", "* Grade(s)", { de: "* Schulstufe(n)", sk: "* Ročník(y)", es: "* Curso(s)", cs: "* Ročník(y)", pl: "* Klasa(y)", pt: "* Ano(s) escolar(es)", it: "* Classe/i" }],
    [".context-fields .half:last-child label", "Age of children (optional)", { de: "Alter der Kinder (optional)", sk: "Vek detí (voliteľné)", es: "Edad de los niños (opcional)", cs: "Věk dětí (volitelné)", pl: "Wiek dzieci (opcjonalnie)", pt: "Idade das crianças (opcional)", it: "Età dei bambini (opzionale)" }],
    [".context-fields .half:first-child .field-note", "Required. Enter one grade or a range, e.g. 4 or 4–6.", { de: "Pflichtfeld. Gib eine Schulstufe oder einen Bereich ein, z. B. 4 oder 4–6.", sk: "Povinné. Zadajte ročník alebo rozsah, napr. 4 alebo 4–6.", es: "Obligatorio. Introduce un curso o un intervalo, por ejemplo 4 o 4–6.", cs: "Povinné. Zadejte ročník nebo rozsah, např. 4 nebo 4–6.", pl: "Wymagane. Podaj klasę lub zakres, np. 4 albo 4–6.", pt: "Obrigatório. Introduza um ano ou intervalo, por exemplo 4 ou 4–6.", it: "Obbligatorio. Inserisci una classe o un intervallo, ad esempio 4 o 4–6." }],
    [".context-fields .half:last-child .field-note", "Optional. e.g. 11", { de: "Optional, z. B. 11", sk: "Voliteľné, napr. 11", es: "Opcional, p. ej. 11", cs: "Volitelné, např. 11", pl: "Opcjonalnie, np. 11", pt: "Opcional, por exemplo 11", it: "Opzionale, ad es. 11" }],
    [".specifics-field > label", "Specifics (optional)", { de: "Zusätzliche Angaben (optional)", sk: "Špecifiká (voliteľné)", es: "Detalles (opcional)", cs: "Upřesnění (volitelné)", pl: "Szczegóły (opcjonalnie)", pt: "Especificidades (opcional)", it: "Dettagli (opzionale)" }],
    [".specifics-field .field-helper", "Special needs, project type, focus areas, etc.", { de: "Besondere Bedürfnisse, Projekttyp, Schwerpunkte usw.", sk: "Špeciálne potreby, typ projektu, oblasti zamerania atď.", es: "Necesidades especiales, tipo de proyecto, áreas de interés, etc.", cs: "Speciální potřeby, typ projektu, oblasti zaměření apod.", pl: "Specjalne potrzeby, typ projektu, obszary zainteresowania itp.", pt: "Necessidades especiais, tipo de projeto, áreas de foco, etc.", it: "Esigenze speciali, tipo di progetto, aree di interesse, ecc." }],
    [".upload-field > label", "* Upload your lesson plan", { de: "* Lade deinen Lesson Plan hoch", sk: "* Nahrajte svoj plán vyučovania", es: "* Sube tu plan de clase", cs: "* Nahrajte svůj plán lekce", pl: "* Prześlij swój plan lekcji", pt: "* Carregue o seu plano de aula", it: "* Carica il tuo piano di lezione" }],
    [".dropzone-text", "Drag & drop your file here", { de: "Ziehe deine Datei hierher", sk: "Presuňte súbor sem", es: "Arrastra tu archivo aquí", cs: "Přetáhněte soubor sem", pl: "Przeciągnij plik tutaj", pt: "Arraste o ficheiro para aqui", it: "Trascina qui il file" }],
    [".dropzone-subtext", "or click to browse", { de: "oder klicke zum Auswählen", sk: "alebo kliknite na výber", es: "o haz clic para buscar", cs: "nebo klikněte pro výběr", pl: "lub kliknij, aby wybrać", pt: "ou clique para procurar", it: "oppure fai clic per cercare" }],
    [".dropzone-hint", "Accepted: PDF, DOCX, TXT • max. 20 MB", { de: "Erlaubt: PDF, DOCX, TXT • max. 20 MB", sk: "Povolené: PDF, DOCX, TXT • max. 20 MB", es: "Permitidos: PDF, DOCX, TXT • máx. 20 MB", cs: "Povoleno: PDF, DOCX, TXT • max. 20 MB", pl: "Dozwolone: PDF, DOCX, TXT • maks. 20 MB", pt: "Aceites: PDF, DOCX, TXT • máx. 20 MB", it: "Accettati: PDF, DOCX, TXT • max. 20 MB" }],
    [".lesson-form .form-actions .secondary-button .button-text", "Back", { de: "Zurück", sk: "Späť", es: "Atrás", cs: "Zpět", pl: "Wstecz", pt: "Voltar", it: "Indietro" }],
    ["#continueButton .button-text", "Continue", { de: "Weiter", sk: "Pokračovať", es: "Continuar", cs: "Pokračovat", pl: "Dalej", pt: "Continuar", it: "Continua" }],
    ["#addCountryButton", "Add country to list", { de: "Land zur Liste hinzufügen", sk: "Pridať krajinu do zoznamu", es: "Añadir país a la lista", cs: "Přidat zemi do seznamu", pl: "Dodaj kraj do listy", pt: "Adicionar país à lista", it: "Aggiungi paese all'elenco" }],
    ["#addSubjectButton", "Add subject to list", { de: "Fach zur Liste hinzufügen", sk: "Pridať predmet do zoznamu", es: "Añadir asignatura a la lista", cs: "Přidat předmět do seznamu", pl: "Dodaj przedmiot do listy", pt: "Adicionar disciplina à lista", it: "Aggiungi materia all'elenco" }],
    ["#countryOther", "Please specify", { de: "Bitte angeben", sk: "Uveďte", es: "Especifica", cs: "Upřesněte", pl: "Określ", pt: "Especifique", it: "Specifica" }],
    ["#subjectOther", "Please specify", { de: "Bitte angeben", sk: "Uveďte", es: "Especifica", cs: "Upřesněte", pl: "Określ", pt: "Especifique", it: "Specifica" }],
    [".help-title", "Why we ask", { de: "Warum wir fragen", sk: "Prečo sa pýtame", es: "Por qué preguntamos", cs: "Proč se ptáme", pl: "Dlaczego pytamy", pt: "Por que perguntamos", it: "Perché lo chiediamo" }],
    [".help-box p:not(.help-title)", "Your information helps us adapt the feedback to your context and curriculum.", { de: "Deine Angaben helfen uns, das Feedback an deinen Kontext und Lehrplan anzupassen.", sk: "Vaše informácie nám pomáhajú prispôsobiť spätnú väzbu vášmu kontextu a učebným osnovám.", es: "Tu información nos ayuda a adaptar los comentarios a tu contexto y currículo.", cs: "Vaše informace nám pomáhají přizpůsobit zpětnou vazbu vašemu kontextu a učebnímu plánu.", pl: "Podane informacje pomagają dopasować informację zwrotną do Twojego kontekstu i programu.", pt: "As suas informações ajudam-nos a adaptar o feedback ao seu contexto e currículo.", it: "Le tue informazioni ci aiutano ad adattare il feedback al tuo contesto e curricolo." }],
    ["#gradeFrom", "From", { de: "Von", sk: "Od", es: "Desde", cs: "Od", pl: "Od", pt: "De", it: "Da" }],
    ["#gradeTo", "To (optional)", { de: "Bis (optional)", sk: "Do (voliteľné)", es: "Hasta (opcional)", cs: "Do (volitelné)", pl: "Do (opcjonalnie)", pt: "Até (opcional)", it: "A (opzionale)" }],
    ["#ageFrom", "From", { de: "Von", sk: "Od", es: "Desde", cs: "Od", pl: "Od", pt: "De", it: "Da" }],
    ["#ageTo", "To", { de: "Bis", sk: "Do", es: "Hasta", cs: "Do", pl: "Do", pt: "Até", it: "A" }],
    ["#specifics", "Any specific information we should know?", { de: "Gibt es besondere Informationen?", sk: "Sú nejaké špecifické informácie?", es: "¿Hay alguna información específica que debamos conocer?", cs: "Je něco konkrétního, co bychom měli vědět?", pl: "Czy są jakieś szczególne informacje?", pt: "Há alguma informação específica que devamos saber?", it: "Ci sono informazioni specifiche che dovremmo sapere?" }],
    [".form-actions > .action-link", "Back", { de: "Zurück", sk: "Späť", es: "Atrás", cs: "Zpět", pl: "Wstecz", pt: "Voltar", it: "Indietro" }],
    ["#continueButton", "Continue", { de: "Weiter", sk: "Pokračovať", es: "Continuar", cs: "Pokračovat", pl: "Dalej", pt: "Continuar", it: "Continua" }],
    [".language-picker label", "Tutor language", { de: "Tutor-Sprache", sk: "Jazyk tutora", es: "Idioma del tutor", cs: "Jazyk tutora", pl: "Język tutora", pt: "Idioma do tutor", it: "Lingua del tutor" }],
    [".analysis-hero h1", "Here is what we found in your lesson plan", { de: "Das haben wir in deinem Lesson Plan gefunden", sk: "Toto sme našli vo vašom pláne vyučovania", es: "Esto es lo que encontramos en tu plan de clase", cs: "Toto jsme našli ve vašem plánu lekce", pl: "Oto, co znaleźliśmy w Twoim planie lekcji", pt: "Isto é o que encontrámos no seu plano de aula", it: "Ecco cosa abbiamo trovato nel tuo piano di lezione" }],
    [".analysis-summary-panel h2", "Lesson plan summary", { de: "Zusammenfassung des Lesson Plans", sk: "Zhrnutie plánu vyučovania", es: "Resumen del plan de clase", cs: "Shrnutí plánu lekce", pl: "Podsumowanie planu lekcji", pt: "Resumo do plano de aula", it: "Riepilogo del piano di lezione" }],
    [".analysis-summary-box h2", "Next step", { de: "Nächster Schritt", sk: "Ďalší krok", es: "Siguiente paso", cs: "Další krok", pl: "Następny krok", pt: "Próximo passo", it: "Passaggio successivo" }],
    [".analysis-hero-copy", "Review the points below. Select what you would like us to focus on in the next step. You can also add more details or clarify if needed.", { de: "Prüfe die folgenden Punkte. Wähle aus, worauf wir uns im nächsten Schritt konzentrieren sollen. Du kannst außerdem Details ergänzen oder etwas klarstellen.", sk: "Prezrite si body nižšie. Vyberte, na čo sa máme zamerať v ďalšom kroku. V prípade potreby môžete doplniť podrobnosti alebo niečo objasniť.", es: "Revisa los puntos siguientes. Selecciona en qué quieres que nos centremos después. También puedes añadir detalles o aclaraciones.", cs: "Prohlédněte si níže uvedené body. Vyberte, na co se máme zaměřit v dalším kroku. V případě potřeby můžete doplnit podrobnosti nebo něco upřesnit.", pl: "Przejrzyj poniższe punkty. Wybierz, na czym mamy skupić się w następnym kroku. Możesz też dodać szczegóły lub wyjaśnienia.", pt: "Reveja os pontos abaixo. Selecione aquilo em que devemos focar no próximo passo. Também pode adicionar detalhes ou esclarecimentos.", it: "Esamina i punti seguenti. Seleziona su cosa concentrarci nel prossimo passaggio. Puoi anche aggiungere dettagli o chiarimenti." }],
    [".analysis-callout > div:nth-child(2) > p:first-child", "We analyzed your uploaded lesson plan and identified the points below.", { de: "Wir haben deinen hochgeladenen Lesson Plan analysiert und die folgenden Punkte identifiziert.", sk: "Analyzovali sme váš nahraný plán vyučovania a identifikovali sme nasledujúce body.", es: "Hemos analizado tu plan de clase y hemos identificado los puntos siguientes.", cs: "Analyzovali jsme váš nahraný plán lekce a identifikovali následující body.", pl: "Przeanalizowaliśmy przesłany plan lekcji i zidentyfikowaliśmy poniższe punkty.", pt: "Analisámos o seu plano de aula e identificámos os pontos abaixo.", it: "Abbiamo analizzato il piano di lezione caricato e identificato i punti seguenti." }],
    [".analysis-callout-title", "Uploaded file", { de: "Hochgeladene Datei", sk: "Nahraný súbor", es: "Archivo cargado", cs: "Nahraný soubor", pl: "Przesłany plik", pt: "Ficheiro carregado", it: "File caricato" }],
    [".summary-chip:nth-of-type(1) .summary-chip-label", "Detected subjects", { de: "Erkannte Fächer", sk: "Identifikované predmety", es: "Asignaturas detectadas", cs: "Zjištěné předměty", pl: "Wykryte przedmioty", pt: "Disciplinas detetadas", it: "Materie rilevate" }],
    [".summary-chip:nth-of-type(2) .summary-chip-label", "Detected grade range", { de: "Erkannter Schulstufenbereich", sk: "Identifikovaný rozsah ročníkov", es: "Intervalo de cursos detectado", cs: "Zjištěný rozsah ročníků", pl: "Wykryty zakres klas", pt: "Intervalo de anos detetado", it: "Intervallo di classi rilevato" }],
    [".summary-chip:nth-of-type(3) .summary-chip-label", "Detected age range", { de: "Erkannter Altersbereich", sk: "Identifikovaný vekový rozsah", es: "Intervalo de edad detectado", cs: "Zjištěný věkový rozsah", pl: "Wykryty zakres wieku", pt: "Intervalo de idades detetado", it: "Intervallo di età rilevato" }],
    [".ct-analysis-panel h2", "Computational Thinking", { de: "Computational Thinking", sk: "Výpočtové myslenie", es: "Pensamiento computacional", cs: "K informatickému myšlení", pl: "Myślenie komputacyjne", pt: "Pensamento computacional", it: "Pensiero computazionale" }],
    [".ct-analysis-intro", "Evidence-based feedback on computational thinking practices performed by learners in the lesson plan.", { de: "Evidenzbasiertes Feedback zu Computational-Thinking-Praktiken, die Lernende im Lesson Plan ausführen.", sk: "Spätná väzba založená na dôkazoch o postupoch výpočtového myslenia, ktoré žiaci vykonávajú v pláne vyučovania.", es: "Comentarios basados en evidencias sobre prácticas de pensamiento computacional realizadas por el alumnado.", cs: "Zpětná vazba založená na důkazech o postupech informatického myšlení, které žáci v plánu lekce provádějí.", pl: "Informacja zwrotna oparta na dowodach dotycząca praktyk myślenia komputacyjnego wykonywanych przez uczniów.", pt: "Feedback baseado em evidências sobre práticas de pensamento computacional realizadas pelos alunos.", it: "Feedback basato su evidenze sulle pratiche di pensiero computazionale svolte dagli studenti." }],
    [".analysis-upload-title", "Upload additional documents (optional)", { de: "Zusätzliche Dokumente hochladen (optional)", sk: "Nahrať ďalšie dokumenty (voliteľné)", es: "Subir documentos adicionales (opcional)", cs: "Nahrát další dokumenty (volitelné)", pl: "Prześlij dodatkowe dokumenty (opcjonalnie)", pt: "Carregar documentos adicionais (opcional)", it: "Carica documenti aggiuntivi (opzionale)" }],
    [".analysis-upload-box > p:nth-of-type(2)", "Drag & drop your file here or click to browse", { de: "Datei hierher ziehen oder zum Auswählen klicken", sk: "Presuňte súbor sem alebo kliknite na výber", es: "Arrastra el archivo aquí o haz clic para buscarlo", cs: "Přetáhněte soubor sem nebo klikněte pro výběr", pl: "Przeciągnij plik tutaj lub kliknij, aby go wybrać", pt: "Arraste o ficheiro para aqui ou clique para procurar", it: "Trascina qui il file o fai clic per cercarlo" }],
    ["#citationModalTitle", "Citation preview", { de: "Zitatvorschau", sk: "Náhľad citácie", es: "Vista previa de la cita", cs: "Náhled citace", pl: "Podgląd cytatu", pt: "Pré-visualização da citação", it: "Anteprima della citazione" }],
    ["#privacyModalTitle", "Personal data detected", { de: "Persönliche Daten erkannt", sk: "Zistené osobné údaje", es: "Datos personales detectados", cs: "Zjištěny osobní údaje", pl: "Wykryto dane osobowe", pt: "Dados pessoais detetados", it: "Dati personali rilevati" }],
    ["#closeCitationModal", "Close", { de: "Schließen", sk: "Zavrieť", es: "Cerrar", cs: "Zavřít", pl: "Zamknij", pt: "Fechar", it: "Chiudi" }],
    ["#confirmPrivacyExamples", "Continue - examples only", { de: "Weiter - nur Beispiele", sk: "Pokračovať - iba príklady", es: "Continuar - solo ejemplos", cs: "Pokračovat - pouze příklady", pl: "Kontynuuj - tylko przykłady", pt: "Continuar - apenas exemplos", it: "Continua - solo esempi" }],
    ["#downloadAnalysisButton .button-text", "Download analysis (DOCX)", { de: "Analyse herunterladen (DOCX)", sk: "Stiahnuť analýzu (DOCX)", es: "Descargar análisis (DOCX)", cs: "Stáhnout analýzu (DOCX)", pl: "Pobierz analizę (DOCX)", pt: "Descarregar análise (DOCX)", it: "Scarica analisi (DOCX)" }],
    [".refinement-hero h1", "Refinement dialogue", { de: "Überarbeitungsdialog", sk: "Dialóg úprav", es: "Diálogo de mejora", cs: "Dialog úprav", pl: "Dialog doskonalenia", pt: "Diálogo de aperfeiçoamento", it: "Dialogo di miglioramento" }],
    ["#refinementOverviewTitle", "Refinement overview", { de: "Überblick zur Überarbeitung", sk: "Prehľad úprav", es: "Resumen de mejoras", cs: "Přehled úprav", pl: "Przegląd doskonalenia", pt: "Visão geral do aperfeiçoamento", it: "Panoramica del miglioramento" }],
    ["#clearConversationButton", "Clear conversation", { de: "Unterhaltung löschen", sk: "Vymazať konverzáciu", es: "Borrar conversación", cs: "Vymazat konverzaci", pl: "Wyczyść rozmowę", pt: "Limpar conversa", it: "Cancella conversazione" }],
    [".refinement-preview-panel .refinement-panel-title", "My lesson plan", { de: "Mein Lesson Plan", sk: "Môj plán vyučovania", es: "Mi plan de clase", cs: "Můj plán lekce", pl: "Mój plan lekcji", pt: "O meu plano de aula", it: "Il mio piano di lezione" }],
    [".refinement-preview-panel .refinement-panel-subtitle", "Summary:", { de: "Zusammenfassung:", sk: "Zhrnutie:", es: "Resumen:", cs: "Shrnutí:", pl: "Podsumowanie:", pt: "Resumo:", it: "Riepilogo:" }],
    ["#downloadDocxButton .button-text", "Download DOCX", { de: "DOCX herunterladen", sk: "Stiahnuť DOCX", es: "Descargar DOCX", cs: "Stáhnout DOCX", pl: "Pobierz DOCX", pt: "Descarregar DOCX", it: "Scarica DOCX" }],
    ["#downloadPdfButton .button-text", "Download PDF", { de: "PDF herunterladen", sk: "Stiahnuť PDF", es: "Descargar PDF", cs: "Stáhnout PDF", pl: "Pobierz PDF", pt: "Descarregar PDF", it: "Scarica PDF" }],
    [".download-stage-header h2", "Final lesson plan preview", { de: "Vorschau des finalen Lesson Plans", sk: "Náhľad finálneho plánu vyučovania", es: "Vista previa del plan de clase final", cs: "Náhled finálního plánu lekce", pl: "Podgląd końcowego planu lekcji", pt: "Pré-visualização do plano de aula final", it: "Anteprima del piano di lezione finale" }],
    [".download-stage-header p", "Please review the final version of your lesson plan before saving or downloading.", { de: "Prüfe die finale Version deines Lesson Plans vor dem Speichern oder Herunterladen.", sk: "Pred uložením alebo stiahnutím skontrolujte finálnu verziu plánu vyučovania.", es: "Revisa la versión final de tu plan de clase antes de guardarlo o descargarlo.", cs: "Před uložením nebo stažením zkontrolujte finální verzi plánu lekce.", pl: "Przed zapisaniem lub pobraniem sprawdź końcową wersję planu lekcji.", pt: "Reveja a versão final do seu plano de aula antes de guardar ou descarregar.", it: "Controlla la versione finale del piano di lezione prima di salvarla o scaricarla." }],
    ["#printPreviewButton .button-text", "Print preview", { de: "Druckvorschau", sk: "Náhľad tlače", es: "Vista previa de impresión", cs: "Náhled tisku", pl: "Podgląd wydruku", pt: "Pré-visualização de impressão", it: "Anteprima di stampa" }],
    [".download-note", "This is the final preview. You can now download the DOCX or the PDF.", { de: "Dies ist die finale Vorschau. Du kannst jetzt DOCX oder PDF herunterladen.", sk: "Toto je finálny náhľad. Teraz si môžete stiahnuť DOCX alebo PDF.", es: "Esta es la vista previa final. Ahora puedes descargar el DOCX o el PDF.", cs: "Toto je finální náhled. Nyní můžete stáhnout DOCX nebo PDF.", pl: "To jest końcowy podgląd. Możesz teraz pobrać DOCX lub PDF.", pt: "Esta é a pré-visualização final. Pode agora descarregar o DOCX ou o PDF.", it: "Questa è l'anteprima finale. Ora puoi scaricare il DOCX o il PDF." }],
    [".download-bottom-actions > .secondary-button:first-child", "Back to editing", { de: "Zurück zum Bearbeiten", sk: "Späť na úpravy", es: "Volver a editar", cs: "Zpět k úpravám", pl: "Wróć do edycji", pt: "Voltar à edição", it: "Torna alla modifica" }],
    ["#copyClipboardButton .button-text", "Copy to clipboard", { de: "In Zwischenablage kopieren", sk: "Kopírovať do schránky", es: "Copiar al portapapeles", cs: "Kopírovat do schránky", pl: "Kopiuj do schowka", pt: "Copiar para a área de transferência", it: "Copia negli appunti" }],
    ["#finishButton .button-text", "Finish lesson plan", { de: "Lesson Plan abschließen", sk: "Dokončiť plán vyučovania", es: "Finalizar el plan de clase", cs: "Dokončit plán lekce", pl: "Zakończ plan lekcji", pt: "Concluir o plano de aula", it: "Completa il piano di lezione" }],
    [".download-side .download-aside-card:nth-of-type(1) h3", "Changes based on our discussion", { de: "Änderungen aus unserer Diskussion", sk: "Zmeny podľa našej diskusie", es: "Cambios basados en nuestra conversación", cs: "Změny podle naší diskuse", pl: "Zmiany wynikające z naszej rozmowy", pt: "Alterações com base na nossa conversa", it: "Modifiche basate sulla nostra discussione" }],
    [".download-side .download-aside-card:nth-of-type(2) h3", "Initial strengths we identified", { de: "Erkannte ursprüngliche Stärken", sk: "Identifikované pôvodné silné stránky", es: "Fortalezas iniciales identificadas", cs: "Identifikované počáteční silné stránky", pl: "Zidentyfikowane początkowe mocne strony", pt: "Pontos fortes iniciais identificados", it: "Punti di forza iniziali identificati" }],
    ["#viewAllChangesButton", "View all changes", { de: "Alle Änderungen anzeigen", sk: "Zobraziť všetky zmeny", es: "Ver todos los cambios", cs: "Zobrazit všechny změny", pl: "Pokaż wszystkie zmiany", pt: "Ver todas as alterações", it: "Mostra tutte le modifiche" }],
    ["#viewAllStrengthsButton", "View all strengths", { de: "Alle Stärken anzeigen", sk: "Zobraziť všetky silné stránky", es: "Ver todas las fortalezas", cs: "Zobrazit všechny silné stránky", pl: "Pokaż wszystkie mocne strony", pt: "Ver todos os pontos fortes", it: "Mostra tutti i punti di forza" }],
    ["#historyModalTitle", "Change history", { de: "Änderungsverlauf", sk: "História zmien", es: "Historial de cambios", cs: "Historie změn", pl: "Historia zmian", pt: "Histórico de alterações", it: "Cronologia delle modifiche" }],
    ["#closeHistoryModal", "Close", { de: "Schließen", sk: "Zavrieť", es: "Cerrar", cs: "Zavřít", pl: "Zamknij", pt: "Fechar", it: "Chiudi" }],
    [".info-page-title", "How the tutor works", { de: "So funktioniert der Tutor", sk: "Ako tutor funguje", es: "Cómo funciona el tutor", cs: "Jak tutor funguje", pl: "Jak działa tutor", pt: "Como funciona o tutor", it: "Come funziona o tutor" }],
    [".info-section:nth-of-type(1) h2", "🚀 First-time setup", { de: "🚀 Einrichtung beim ersten Start", sk: "🚀 Prvé nastavenie", es: "🚀 Configuración inicial", cs: "🚀 První nastavení", pl: "🚀 Pierwsza konfiguracja", pt: "🚀 Configuração inicial", it: "🚀 Configurazione iniziale" }],
    [".info-section:nth-of-type(2) h2", "🧭 Your tutor workflow", { de: "🧭 Dein Tutor-Workflow", sk: "🧭 Postup práce s tutorom", es: "🧭 Flujo de trabajo del tutor", cs: "🧭 Pracovní postup tutora", pl: "🧭 Przebieg pracy z tutorem", pt: "🧭 Fluxo de trabalho do tutor", it: "🧭 Flusso di lavoro del tutor" }],
    [".info-step-card:nth-of-type(1) h3", "📁 Get the tutor", { de: "📁 Tutor herunterladen", sk: "📁 Získajte tutora", es: "📁 Obtener el tutor", cs: "📁 Získejte tutora", pl: "📁 Pobierz tutora", pt: "📁 Obter o tutor", it: "📁 Ottenere il tutor" }],
    [".info-step-card:nth-of-type(2) h3", "▶️ Start it", { de: "▶️ Tutor starten", sk: "▶️ Spustite ho", es: "▶️ Iniciarlo", cs: "▶️ Spusťte ho", pl: "▶️ Uruchom go", pt: "▶️ Iniciá-lo", it: "▶️ Avviarlo" }],
    [".info-step-card:nth-of-type(3) h3", "🔑 Add your API key", { de: "🔑 API-Key eintragen", sk: "🔑 Pridajte API kľúč", es: "🔑 Añadir tu clave API", cs: "🔑 Přidejte svůj API klíč", pl: "🔑 Dodaj swój klucz API", pt: "🔑 Adicionar a sua chave API", it: "🔑 Aggiungi la tua chiave API" }],
    [".info-step-card:nth-of-type(4) h3", "✅ Start working", { de: "✅ Loslegen", sk: "✅ Začnite pracovať", es: "✅ Empezar a trabajar", cs: "✅ Začněte pracovat", pl: "✅ Zacznij pracę", pt: "✅ Começar a trabalhar", it: "✅ Iniciar o trabalho" }],
    [".info-feature-card:nth-of-type(1) h3", "1. Describe your lesson", { de: "1. Beschreibe deine Unterrichtsstunde", sk: "1. Opíšte svoju hodinu", es: "1. Describe tu clase", cs: "1. Popište svou lekci", pl: "1. Opisz swoją lekcję", pt: "1. Descreva a sua aula", it: "1. Descrivi la tua lezione" }],
    [".info-feature-card:nth-of-type(2) h3", "2. Review the analysis", { de: "2. Prüfe die Analyse", sk: "2. Prezrite si analýzu", es: "2. Revisa el análisis", cs: "2. Prohlédněte si analýzu", pl: "2. Przejrzyj analizę", pt: "2. Reveja a análise", it: "2. Esamina l'analisi" }],
    [".info-feature-card:nth-of-type(3) h3", "3. Refine the plan", { de: "3. Überarbeite den Plan", sk: "3. Upravte plán", es: "3. Mejora el plan", cs: "3. Upravte plán", pl: "3. Udoskonal plan", pt: "3. Aperfeiçoe o plano", it: "3. Perfeziona il piano" }],
    [".info-feature-card:nth-of-type(4) h3", "4. Download the result", { de: "4. Ergebnis herunterladen", sk: "4. Stiahnite výsledok", es: "4. Descarga el resultado", cs: "4. Stáhněte výsledek", pl: "4. Pobierz wynik", pt: "4. Descarregue o resultado", it: "4. Scarica il risultato" }],
    [".info-page-title + p.description", "The AI tutor analyses your uploaded lesson plan and offers structured feedback in categories such as didactical approaches, skills, curriculum connections, potential challenges, and opportunities.", { de: "Der KI-Tutor analysiert deinen hochgeladenen Lesson Plan und gibt strukturiertes Feedback zu Didaktik, Kompetenzen, Lehrplanbezügen, möglichen Herausforderungen und Chancen.", sk: "AI tutor analyzuje váš nahraný plán vyučovania a poskytuje štruktúrovanú spätnú väzbu k didaktickým prístupom, zručnostiam, učebným osnovám, výzvam a príležitostiam.", es: "El tutor de IA analiza tu plan de clase y ofrece comentarios estructurados sobre didáctica, competencias, currículo, posibles retos y oportunidades.", cs: "AI tutor analyzuje váš nahraný plán lekce a poskytuje strukturovanou zpětnou vazbu k didaktice, dovednostem, učebním plánům, výzvám a příležitostem.", pl: "Tutor AI analizuje przesłany plan lekcji i przekazuje uporządkowaną informację zwrotną o dydaktyce, umiejętnościach, programie, wyzwaniach i możliwościach.", pt: "O tutor de IA analisa o plano de aula carregado e fornece feedback estruturado sobre didática, competências, currículo, desafios e oportunidades.", it: "Il tutor IA analizza il piano di lezione caricato e offre feedback strutturato su didattica, competenze, curricolo, sfide e opportunità." }],
    [".project-info-title + p.description", "The STEaiM-CT prototype is designed to support teachers in reflecting on didactics, skills, structure, and curriculum alignment in their lesson plans.", { de: "Der STEaiM-CT-Prototyp unterstützt Lehrkräfte dabei, über Didaktik, Kompetenzen, Struktur und Lehrplanbezug ihrer Lesson Plans zu reflektieren.", sk: "Prototyp STEaiM-CT podporuje učiteľov pri reflexii didaktiky, zručností, štruktúry a súladu s učebnými osnovami.", es: "El prototipo STEaiM-CT ayuda al profesorado a reflexionar sobre didáctica, competencias, estructura y alineación curricular.", cs: "Prototyp STEaiM-CT pomáhá učitelům reflektovat didaktiku, dovednosti, strukturu a soulad s učebními plány.", pl: "Prototyp STEaiM-CT wspiera nauczycieli w refleksji nad dydaktyką, umiejętnościami, strukturą i zgodnością z programem.", pt: "O protótipo STEaiM-CT apoia os professores na reflexão sobre didática, competências, estrutura e alinhamento curricular.", it: "Il prototipo STEaiM-CT aiuta gli insegnanti a riflettere su didattica, competenze, struttura e allineamento curricolare." }],
    [".info-note strong", "💡 What you need", { de: "💡 Was du brauchst", sk: "💡 Čo potrebujete", es: "💡 Lo que necesitas", cs: "💡 Co potřebujete", pl: "💡 Czego potrzebujesz", pt: "💡 O que precisa", it: "💡 Cosa serve" }],
    [".privacy-note strong", "🔒 Your data and API key", { de: "🔒 Deine Daten und der API-Key", sk: "🔒 Vaše údaje a API kľúč", es: "🔒 Tus datos y la clave API", cs: "🔒 Vaše data a API klíč", pl: "🔒 Twoje dane i klucz API", pt: "🔒 Os seus dados e a chave API", it: "🔒 I tuoi dati e la chiave API" }],
    [".project-info-title", "About STEaiM-CT", { de: "Über STEaiM-CT", sk: "O projekte STEaiM-CT", es: "Sobre STEaiM-CT", cs: "O projektu STEaiM-CT", pl: "O STEaiM-CT", pt: "Sobre o STEaiM-CT", it: "Informazioni su STEaiM-CT" }],
    [".settings-card > .description", "This area shows local configuration status for the tutor. Secrets stay in a local key file and are never displayed or committed here.", { de: "Hier siehst du den Status der lokalen Tutor-Konfiguration. Geheimnisse bleiben in einer lokalen Schlüsseldatei und werden hier weder angezeigt noch eingecheckt.", sk: "Táto časť zobrazuje stav miestnej konfigurácie tutora. Tajomstvá zostávajú v miestnom súbore s kľúčom a tu sa nikdy nezobrazujú ani necommitujú.", es: "Aquí se muestra el estado de la configuración local del tutor. Los secretos permanecen en un archivo de claves local y nunca se muestran ni se incluyen aquí.", cs: "Tato část zobrazuje stav místní konfigurace tutora. Tajné údaje zůstávají v místním souboru s klíčem a zde se nezobrazují ani necommitují.", pl: "Ta sekcja pokazuje stan lokalnej konfiguracji tutora. Sekrety pozostają w lokalnym pliku klucza i nie są tutaj wyświetlane ani commitowane.", pt: "Esta área mostra o estado da configuração local do tutor. Os segredos permanecem num ficheiro de chave local e nunca são apresentados nem incluídos aqui.", it: "Questa area mostra lo stato della configurazione locale del tutor. I segreti restano in un file chiave locale e non vengono mai mostrati o inclusi qui." }],
    [".settings-panel:nth-of-type(1) h2", "Mistral API", { de: "Mistral-API", sk: "Mistral API", es: "API de Mistral", cs: "Mistral API", pl: "API Mistral", pt: "API Mistral", it: "API Mistral" }],
    [".settings-panel:nth-of-type(2) h2", "Curricula", { de: "Lehrpläne", sk: "Učebné osnovy", es: "Currículos", cs: "Učební plány", pl: "Programy nauczania", pt: "Currículos", it: "Curricoli" }],
    [".settings-panel:nth-of-type(3) h2", "Local logs", { de: "Lokale Logs", sk: "Miestne logy", es: "Registros locales", cs: "Místní protokoly", pl: "Lokalne logi", pt: "Registos locais", it: "Log locali" }],
    [".startup-status-heading h2", "🩺 System check", { de: "🩺 Systemprüfung", sk: "🩺 Kontrola systému", es: "🩺 Comprobación del sistema", cs: "🩺 Kontrola systému", pl: "🩺 Kontrola systemu", pt: "🩺 Verificação do sistema", it: "🩺 Controllo del sistema" }],
    [".settings-note:not(.startup-status) h2", "Prompt files", { de: "Prompt-Dateien", sk: "Súbory promptov", es: "Archivos de prompts", cs: "Soubory promptů", pl: "Pliki promptów", pt: "Ficheiros de prompts", it: "File dei prompt" }],
    [".settings-form h2", "Mistral / AI connection", { de: "Mistral-/KI-Verbindung", sk: "Pripojenie Mistral / AI", es: "Conexión Mistral / IA", cs: "Připojení Mistral / AI", pl: "Połączenie Mistral / AI", pt: "Ligação Mistral / IA", it: "Connessione Mistral / IA" }],
    [".settings-save-button .button-text", "Save settings", { de: "Einstellungen speichern", sk: "Uložiť nastavenia", es: "Guardar configuración", cs: "Uložit nastavení", pl: "Zapisz ustawienia", pt: "Guardar definições", it: "Salva impostazioni" }],
    [".settings-actions .button-text", "Back to start", { de: "Zurück zum Start", sk: "Späť na začiatok", es: "Volver al inicio", cs: "Zpět na začátek", pl: "Wróć do początku", pt: "Voltar ao início", it: "Torna all'inizio" }],
    [".settings-eyebrow", "Local administration", { de: "Lokale Verwaltung", sk: "Lokálna správa", es: "Administración local", cs: "Místní správa", pl: "Administracja lokalna", pt: "Administração local", it: "Amministrazione locale" }],
    [".settings-card h1", "Admin settings", { de: "Admin-Einstellungen", sk: "Nastavenia správcu", es: "Configuración de administración", cs: "Nastavení správce", pl: "Ustawienia administratora", pt: "Definições de administração", it: "Impostazioni amministratore" }]
  ];

  function currentLanguage() {
    return languageKeys[window.localStorage.getItem("preferredLanguage") || "English"] || "en";
  }

  function translate(entry, language) {
    return entry[2][language] || entry[1];
  }

  function applyTranslations() {
    var language = currentLanguage();
    document.documentElement.lang = language;
    translations.forEach(function (entry) {
      var element = document.querySelector(entry[0]);
      if (!element) {
        return;
      }
      var text = translate(entry, language);
      if (element.tagName === "INPUT" || element.tagName === "TEXTAREA") {
        if (element.getAttribute("placeholder")) {
          element.setAttribute("placeholder", text);
        }
      } else {
        element.textContent = text;
      }
    });
    var countrySelect = document.getElementById("country");
    if (countrySelect && countrySelect.options.length) {
      var labels = { en: "Select country", de: "Land auswählen", sk: "Vyberte krajinu", es: "Selecciona un país", cs: "Vyberte zemi", pl: "Wybierz kraj", pt: "Selecione o país", it: "Seleziona il paese" };
      countrySelect.options[0].textContent = labels[language] || labels.en;
    }
  }

  window.tutorTranslate = function (key, fallback) {
    var language = currentLanguage();
    if (messageTranslations[key]) {
      return messageTranslations[key][language] || key;
    }
    for (var index = 0; index < translations.length; index += 1) {
      if (translations[index][1] === key) {
        return translate(translations[index], language);
      }
    }
    return fallback || key;
  };

  document.addEventListener("DOMContentLoaded", applyTranslations);
  window.addEventListener("languagechange", applyTranslations);
})();
